# Generated by Django 6.0.2 on 2026-03-04 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('salons', '0003_salon_commission_rate'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_due_at_salon',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount to pay at salon (service price)', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform booking fee (10% commission)', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment gateway reference', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Service price at time of booking', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client', 'status'], name='bookings_bo_client__09b1d6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['salon', 'status'], name='bookings_bo_salon_i_9a28dc_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='bookings_bo_booking_f34616_idx'),
        ),
    ]
