# Generated by Django 4.2.30 on 2026-04-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_price_booking_amount_due_at_salon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_required',
            field=models.BooleanField(default=False, help_text='True if this booking was created outside the free period (for future billing).'),
        ),
    ]
