# Generated by Django 4.2.30 on 2026-09-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_workflow_notifications'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customernotification',
            new_name='bookings_cu_recipie_32a0d3_idx',
            old_name='bookings_cu_recipie_idx',
        ),
        migrations.RenameIndex(
            model_name='salonownernotification',
            new_name='bookings_sa_recipie_2c8ddf_idx',
            old_name='bookings_sa_recipie_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='decline_message',
            field=models.TextField(blank=True, help_text='Custom message when decline_reason is "other"', null=True),
        ),
    ]
