# Generated by Django 6.0.2 on 2026-03-07 14:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0003_salon_commission_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Advertisement video file', upload_to='advertisements/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm'])])),
                ('video_thumbnail', models.ImageField(blank=True, help_text='Video thumbnail image', null=True, upload_to='advertisements/thumbnails/')),
                ('tagline', models.CharField(help_text='Short catchy phrase for the advertisement', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional description or details', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('scheduled', 'Scheduled'), ('expired', 'Expired'), ('paused', 'Paused')], default='pending', help_text='Current status of the advertisement', max_length=20)),
                ('start_date', models.DateField(help_text='Advertisement start date')),
                ('end_date', models.DateField(help_text='Advertisement end date')),
                ('views', models.PositiveIntegerField(default=0, help_text='Number of times the ad has been viewed')),
                ('clicks', models.PositiveIntegerField(default=0, help_text='Number of clicks to salon page')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this ad appears in the featured carousel')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the ad was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the ad was last updated')),
                ('salon', models.ForeignKey(help_text='Salon associated with this advertisement', on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='salons.salon')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['status', 'is_featured'], name='admin_porta_status_2a7c76_idx'), models.Index(fields=['start_date', 'end_date'], name='admin_porta_start_d_f4d852_idx')],
            },
        ),
    ]
