# Generated by Django 6.0.2 on 2026-03-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='BeautyBook CM', max_length=100)),
                ('booking_fee_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('min_booking_amount', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('max_booking_days_ahead', models.PositiveIntegerField(default=30)),
                ('allow_multiple_bookings', models.BooleanField(default=True)),
                ('payment_mode', models.CharField(choices=[('momo', 'MoMo (Mobile Money)'), ('cash', 'Cash at Salon'), ('both', 'Both')], default='momo', max_length=10)),
                ('momo_primary_number', models.CharField(blank=True, default='', max_length=20)),
                ('momo_secondary_number', models.CharField(blank=True, default='', max_length=20)),
                ('max_active_ads', models.PositiveIntegerField(default=3)),
                ('default_ad_duration_days', models.PositiveIntegerField(default=30)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('allow_new_registrations', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
