# Generated by Django 4.2.30 on 2026-04-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='payment_enabled',
            field=models.BooleanField(default=False, help_text='Enable payment collection. False = free booking mode for all users.'),
        ),
    ]
