# Generated by Django 6.0.2 on 2026-02-19 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(choices=[('Douala', 'Douala'), ('Yaoundé', 'Yaoundé')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='salon_images/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='salon_covers/')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('review_count', models.IntegerField(default=0)),
                ('starting_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('phone', models.CharField(max_length=20)),
                ('open_hours', models.CharField(max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salon',
                'verbose_name_plural': 'Salons',
                'ordering': ['-rating', '-review_count'],
            },
        ),
    ]
