# Generated by Django 6.0.2 on 2026-02-26 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='mobile_money',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salon',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='workers',
            field=models.CharField(blank=True, choices=[('1-3', '1-3'), ('4-7', '4-7'), ('8-15', '8-15'), ('15+', '15+')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
