# Generated by Django 6.0.2 on 2026-03-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_salon_mobile_money_salon_owner_salon_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Commission rate charged on bookings (default 10%)', max_digits=5),
        ),
    ]
