# Generated by Django 6.0.2 on 2026-04-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_salon_commission_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Set to True by admin after approval'),
        ),
    ]
