# Generated by Django 6.0.2 on 2026-04-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_salon_inactive_by_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='open_hours',
            field=models.CharField(blank=True, default='Mon-Sat: 8AM - 7PM', max_length=100),
        ),
    ]
