# Generated by Django 4.2.30 on 2026-09-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0007_city_blank_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
