# Generated by Django 4.2.30 on 2026-04-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='free_booking_until',
            field=models.DateTimeField(blank=True, help_text='User can book for free until this date. Null = no free period.', null=True),
        ),
    ]
